/**
 * Мапа deprecated иконок, значение означает иконку-заменитель,
 * если значение не указано, значит иконка безнадежно deprecated.
 */
export const deprecationMap = {
    ic_prd_account_default_32_w: '',
    ic_prd_banknote_default_32_w: '',
    ic_prd_banktax_default_20_w: '',
    ic_prd_counterpartypay_default_20_w: '',
    ic_prd_homeservice_default_20_w: '',
    ic_srv_answer_default_20_w: '',
    ic_srv_review_default_20_w: '',
    ic_prd_mailbell_default_32_w: 'ic_nav_mailbell_default_32_w',
    ic_srvx_balance_default_24_w: 'ic_nav_balance_default_24_w',
    ic_prd_changeaccount_default_20_w: 'ic_nav_changeaccount_default_20_w',
    ic_srvx_changeaccount_default_24_w: 'ic_nav_changeaccount_default_24_w',
    ic_srvx_notification_default_24_w: 'ic_nav_notification_default_24_w',
    ic_srvx_notificationnew_default_24_w: 'ic_nav_notificationnew_default_24_w',
    ic_srvx_exit_default_24_w: 'ic_nav_exit_default_24_w',
    ic_srvx_settingsberraiting_default_24_w: 'ic_nav_settingsberraiting_default_24_w',
    ic_prdx_currencyaccountgold_default_32_w: 'ic_prdx_metallaccountgold_default_32_w',
    ic_prdx_currencyaccountpalladium_default_32_w: 'ic_prdx_metallaccountpalladium_default_32_w',
    ic_prdx_currencyaccountplatinum_default_32_w: 'ic_prdx_metallaccountplatinum_default_32_w',
    ic_prdx_currencyaccountsilver_default_32_w: 'ic_prdx_metallaccountsilver_default_32_w',
    ic_prd_buy_default_20_w: '',
    ic_prd_buy_default_32_w: '',
    ic_prd_spasibobusineess_default_20_w: 'ic_prd_spasibobusiness_default_20_w',
    ic_prd_spasibobusineess_default_32_w: 'ic_prd_spasibobusiness_default_32_w',
    ic_nav_barchart_default_20_w: '',
    ic_nav_donutchart_default_20_w: '',
    ic_nav_linechart_default_20_w: '',
    ic_nav_viewlist_default_20_w: '',
    ic_nav_viewlist_default_32_w: '',
    ic_nav_viewplate_default_20_w: '',
    ic_nav_viewplate_default_32_w: '',
    ic_prd_beautyservice_default_20_w: '',
    ic_prd_beautyservice_default_32_w: '',
    ic_sts_oninfoerror_default_16_w: 'ic_sts_noinfoerror_default_16_w',
    ic_sts_oninfowait_default_16_w: 'ic_sts_noinfowait_default_16_w',
    ic_sts_oninfowarning_default_16_w: 'ic_sts_noinfowarning_default_16_w',
    ic_srvx_optionsoff_default_32_w: '',
    ic_srvx_optionson_default_32_w: '',
};
