name: Build Icons

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 10.16.3

      - run: |
          npm install
          npm run build:icons

      - uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/
