name: Build Icons

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - run: |
          npm install
          npm run build:icons

      - uses: actions/upload-artifact@v3
        with:
          name: public
          path: public/
