name: Generate Illustrations

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 10.16.3

      - run: |
          npm install
          npm run generate:illustrations
