name: Publish Illustrations

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Publish icons
        run: |
          npm install
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm run publish:illustrations
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: public
          path: public/
