name: Publish Icons

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16.14.0

      - name: Publish icons
        run: |
          npm ci
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm run publish:icons
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: public
          path: public/
